title:             BlueprintHub
email:             
description:       
author:            Mr. Braz
baseurl:           "/"
url:               ""

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-paginate

collections:
  categories:
    output: true
  blueprints:
    output: true